/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterPatientRouteImport } from './routes/register.patient'
import { Route as RegisterPharmacyRouteImport } from './routes/register.pharmacy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPatientRoute = RegisterPatientRouteImport.update({
  id: '/register/patient',
  path: '/register/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPharmacyRoute = RegisterPharmacyRouteImport.update({
  id: '/register/pharmacy',
  path: '/register/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/register/patient': typeof RegisterPatientRoute
  '/register/pharmacy': typeof RegisterPharmacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/register/patient': typeof RegisterPatientRoute
  '/register/pharmacy': typeof RegisterPharmacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/register/patient': typeof RegisterPatientRoute
  '/register/pharmacy': typeof RegisterPharmacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/get-started' | '/login' | '/register/patient' | '/register/pharmacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/get-started' | '/login' | '/register/patient' | '/register/pharmacy'
  id:
    | '__root__'
    | '/'
    | '/get-started'
    | '/login'
    | '/register/patient'
    | '/register/pharmacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GetStartedRoute: typeof GetStartedRoute
  LoginRoute: typeof LoginRoute
  RegisterPatientRoute: typeof RegisterPatientRoute
  RegisterPharmacyRoute: typeof RegisterPharmacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/patient': {
      id: '/register/patient'
      path: '/register/patient'
      fullPath: '/register/patient'
      preLoaderRoute: typeof RegisterPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/pharmacy': {
      id: '/register/pharmacy'
      path: '/register/pharmacy'
      fullPath: '/register/pharmacy'
      preLoaderRoute: typeof RegisterPharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GetStartedRoute: GetStartedRoute,
  LoginRoute: LoginRoute,
  RegisterPatientRoute: RegisterPatientRoute,
  RegisterPharmacyRoute: RegisterPharmacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
